### ISSUE TITLE
Upgrade to PureScript 0.9.1 and purescript-spec 0.8.0

### ISSUE THREAD

**Issue by owickstrom** [owickstrom/purescript-spec-quickcheck#5]

**Comment by matthewleon** [comment]
This should probably now be shifted to purescript 0.10.x and purescript-spec 0.11.0

**Comment by owickstrom** [comment]
Yes, absolutely. I was meaning to release new versions of all the purescript-spec-* libraries, but wanted to wait for https://github.com/owickstrom/purescript-spec/issues/33 as it will be a breaking change. The plan is to release 1.0 of purescript-spec once that is done. But we could of course do an update here for purescript 0.10.x in the mean time. I'll get on it. :) Thanks!

**Comment by owickstrom** [comment]
No breaking change was needed (except for the effect-related one already released in `0.11.x`) and all packages are released now, so I'm closing this. 

Here are the versions:

* purescript-spec-quickcheck 0.10.0
* purescript-spec-mocha 0.4.0
* purescript-spec-discovery 0.4.0
* purescript-spec-reporter-xunit 0.3.1
* purescript-spec 0.12.0

Thanks!

**Comment by owickstrom** [comment]
Note that `purescript-spec` is 0.12.0 now, although from a user point of view there should be no changes.
